version: '3.7'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: <%= ENV['DB_PASSWORD'] %>
      MYSQL_DATABASE: ruby_dockerize
      MYSQL_PASSWORD: <%= ENV['DB_PASSWORD'] %>

    env_file: .env
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '127.0.0.1'"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    tty: true
    stdin_open: true
volumes:
  mysql-data: